### ISSUE TITLE
PSP 3000 compatibility

### ISSUE THREAD

**Issue by DobaMuffin** [orangeglo/PS2PSP#1]
I am wondering if this would also work with psp 3000 motherboards?

**Comment by epbarger** [comment]
Unfortunately it would not as is - the ribbon cable connections are different between the two models. It would be possible to modify the design to support the 3000 though.

**Comment by DobaMuffin** [comment]
I am currently looking at the necessary steps for 3000 conversion of the pcb. So far it seems almost everything maps out the same, and the board is more or less ready to accept the 3000.

**Comment by epbarger** [comment]
That's great! I was under the impression the 3000 has different size flat flex cables in a few spots, but I may have been misremembering.

**Comment by DobaMuffin** [comment]
It looks like the flat flex cables for the home ribbon are the same, whereas the left ribbon cable is smaller, and the right cable has a slightly different pinout towards the middle. Should be fairly simple to modify the board to support psp 3000. I'll do a bit more investigation, then modify the board design and order them to test if it works. If all is good in the end, then I'll create a merge request for it.

I will try to see if the cables fit though. They look to be the same size, but I may be wrong. Should know by end of the week.

**Comment by epbarger** [comment]
Nice, excellent work. The 3000 also uses a FFC for the joystick connection, so you could take advantage of that as well if you wanted.

**Comment by DobaMuffin** [comment]
Twas my plan. I see the 3 pins for the joystick connection in the original design, and I know they get soldered on the psp 2000, but it will be easy to extend them on the board to a 4 pin ffc connector so that the psp 3000 would be a truly solderless install. I just need to check if the analog stick operates at 2.5v like what I've been reading since I don't want to damage the psp in any way by feeding it a higher voltage on those x and y signals.

**Comment by epbarger** [comment]
You don't need to feed any power into the analog stick FFC, it provides the power and ground that you're using through the two digipots that output X and Y, so it's effectively isolated from the rest of the custom PCB. So the board can't output more than the VCC that is coming in on the FFC pin since that is the voltage going through the digipot

**Comment by DobaMuffin** [comment]
What's the max voltage being sent back from the digipot? I've read that the psp pulses a 2.5v signal to the onboard analog stick, which would mean the max voltage being read from the potentiometers is 2.5v, but I see the digipot is being fed 3.3v in the design, hence my concern for potential damage.

This is also why I need to hook up my oscilloscope to the analog stick connection to test what voltage it expects as a maximum.

**Comment by epbarger** [comment]
2.5v sounds correct to me, but I'm not positive. I remember some parts of the PSP run as low as 1.8v logic. 

The way the circuit is wired, it's not possible for the PSP to get above 2.5v on X or Y unless the digipot chip malfunctioned. The digipot only acts as a voltage divider, so with the inputs of 2.5v and GND from the joystick pins, the output X and Y can only ever be between those two values. If it was the other way around, with the digipot supply at 2.5, and the psp at 3.3, that would have the potential to damage the digipot I believe.

**Comment by DobaMuffin** [comment]
Ah, I see now. Seems I had been misreading the schematic this entire time.

**Comment by DobaMuffin** [comment]
It seems as though the middle bar flex cable from a psp 3000 works in the psp 2000, so that looks to be a direct connection with no changes, the right button ribbon is the same size with the grounds for the power board lights being separate on the psp 3000 vs combined on the psp 2000, and the left side seems to be the same pitch, just with 3 pins less on the connector.

**Comment by DobaMuffin** [comment]
Board design has been modified. I just need to wait a few weeks to make sure it looks good before I order them to test.

**Comment by Bma36** [comment]
Hi, tutorial?

**Comment by amilton33** [comment]
hello
